# Generated by Django 5.0.3 on 2024-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
